###############################################################################
# 
#                   Dockerfile_pytoulbar2plus container 
# 
#  dedicated to pytoulbar2 Python API of toulbar2 + some other python libraries
# 
# Desc ------------------------------------------------------------------------
# 
# Installation with python3 -m pip install pytoulbar2
#                   python3 -m pip install ...
# 
# Build -----------------------------------------------------------------------
#
# To build pytoulbar2plus-docker image :
#
#   docker build -f Dockerfile_pytoulbar2plus -t pytoulbar2plus-docker:latest .
#
# Work inside -----------------------------------------------------------------
#
# Then to work inside pytoulbar2plus-docker image, under /WORK 
# (as local folder to remaining results) :
#
#   docker run -v $PWD:/WORK -ti pytoulbar2plus-docker /bin/bash
#
###############################################################################

FROM ubuntu:20.04

RUN apt-get update -yq \
&& apt-get install git-core -y \
&& apt-get install vim -y \
&& apt-get install python3 -y \
&& apt-get install python3-pip -y \
&& apt-get clean -y

RUN pip3 install --upgrade pip wheel setuptools \
&& pip3 install --upgrade pytoulbar2 \
&& pip3 install --upgrade numpy \
&& pip3 install --upgrade nbconvert \
&& pip3 install --upgrade more-itertools \
&& pip3 install --upgrade matplotlib \
&& pip3 install --upgrade pandas \
&& pip3 install --upgrade tensorflow \
&& pip3 install --upgrade keras \
&& pip3 install --upgrade sklearn \
&& pip3 install --upgrade imutils \
&& pip3 install --upgrade opencv-python \
&& pip3 install --upgrade opencv-python-headless \
&& pip3 install --upgrade scikit-image

RUN mkdir /WORK

###############################################################################

