###############################################################################
# 
#                   Dockerfile_pytoulbar2plus container 
# 
#  dedicated to pytoulbar2 Python API of toulbar2 + some other python libraries
# 
# Desc ------------------------------------------------------------------------
# 
# Installation with python3 -m pip install pytoulbar2
#                   python3 -m pip install ...
# 
# Build -----------------------------------------------------------------------
#
# To build pytoulbar2plus-docker image :
#
#   docker build -f Dockerfile_pytoulbar2plus -t pytoulbar2plus-docker:latest .
#
# Work inside -----------------------------------------------------------------
#
# Then to work inside pytoulbar2plus-docker image, under /WORK 
# (as local folder to remaining results) :
#
#   docker run -v $PWD:/WORK -ti pytoulbar2plus-docker /bin/bash
#
###############################################################################

FROM debian:buster-slim

RUN apt-get update -yq \
&& apt-get install git-core -y \
&& apt-get install vim -y \
&& apt-get install python3 -y \
&& apt-get install python3-pip -y \
&& apt-get clean -y

RUN python3 -m pip install --upgrade pip wheel setuptools \
&& python3 -m pip install --upgrade pytoulbar2 \
&& python3 -m pip install --upgrade numpy \
&& python3 -m pip install --upgrade nbconvert \
&& python3 -m pip install --upgrade more-itertools \
&& python3 -m pip install --upgrade matplotlib \
&& python3 -m pip install --upgrade pandas \
&& python3 -m pip install --upgrade tensorflow \
&& python3 -m pip install --upgrade keras \
&& python3 -m pip install --upgrade sklearn \
&& python3 -m pip install --upgrade imutils \
&& python3 -m pip install --upgrade opencv-python \
&& python3 -m pip install --upgrade opencv-python-headless \
&& python3 -m pip install --upgrade scikit-image

RUN mkdir /WORK

###############################################################################

