###############################################################################
# 
#                   Dockerfile_pytoulbar2plus container 
# 
#  dedicated to pytoulbar2 Python API of toulbar2 + some other python libraries
# 
# Desc ------------------------------------------------------------------------
# 
# Installation with python3 -m pip install pytoulbar2
#                   python3 -m pip install ...
# 
# Build -----------------------------------------------------------------------
#
# To build pytoulbar2plus-docker image :
#
#   docker build -f Dockerfile_pytoulbar2plus -t pytoulbar2plus-docker:latest .
#
# Work inside -----------------------------------------------------------------
#
# Then to work inside pytoulbar2plus-docker image, under /WORK 
# (as local folder to remaining results) :
#
#   docker run -v $PWD:/WORK -ti pytoulbar2plus-docker /bin/bash
#
###############################################################################

FROM debian:buster-slim

RUN apt-get update -yq \
&& apt-get install git-core -y \
&& apt-get install vim -y \
&& apt-get install python3 -y \
&& apt-get install python3-pip -y \
&& apt-get clean -y

RUN python3 -m pip install --upgrade pip wheel setuptools -y \
&& python3 -m pip install --upgrade pytoulbar2 -y \
&& python3 -m pip install --upgrade numpy -y \
&& python3 -m pip install --upgrade nbconvert -y \
&& python3 -m pip install --upgrade more-itertools -y \
&& python3 -m pip install --upgrade matplotlib -y \
&& python3 -m pip install --upgrade pandas -y \
&& python3 -m pip install --upgrade tensorflow-cpu -y \
&& python3 -m pip install --upgrade keras -y \
&& python3 -m pip install --upgrade sklearn -y \
&& python3 -m pip install --upgrade imutils -y \
&& python3 -m pip install --upgrade opencv-python -y \
&& python3 -m pip install --upgrade opencv-python-headless -y \
&& python3 -m pip install --upgrade scikit-image -y \
&& python3 -m pip uninstall opencv-python-headless -y \
&& python3 -m pip uninstall opencv-python -y \
&& python3 -m pip install opencv-python -y

RUN mkdir /WORK

###############################################################################

