name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# memo
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_ROOT: ${{ github.repository }}

jobs:

# build-and-push-image-toulbar2:

#   runs-on: ubuntu-latest
#   permissions:
#     contents: read
#     packages: write

#   steps:

#     - name: Checkout repository
#       uses: actions/checkout@v2

#     # Login against a Docker registry except on PR
#     # https://github.com/docker/login-action
#     - name: Log into registry ${{ env.REGISTRY }}
#       if: github.event_name != 'pull_request'
#       uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
#       with:
#         registry: ${{ env.REGISTRY }}
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}

#     # Extract metadata (tags, labels) for Docker
#     # https://github.com/docker/metadata-action
#     - name: Extract Docker metadata
#       id: meta
#       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#       with:
#         images: ${{ env.REGISTRY }}/${{ env.IMAGE_ROOT }}/toulbar2


#     # Build and push Docker image with Buildx (don't push on PR)
#     # https://github.com/docker/build-push-action
#     - name: Build and push Docker image toulbar2
#       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#       with:
#         context: .
#         file: ./docker/toulbar2/Dockerfile
#         push: ${{ github.event_name != 'pull_request' }}
#         tags: ${{ steps.meta.outputs.tags }}
#         labels: ${{ steps.meta.outputs.labels }}

  build-and-push-image-pytoulbar2:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_ROOT }}/pytoulbar2


      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image pytoulbar2
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./docker/pytoulbar2/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


